### ISSUE TITLE
In `validate_password` method both `isascii()` and `isalpha()` functions are used.

### ISSUE THREAD

**Issue by armgabrielyan** [Areg2001/Password_managemnet#6]
**Level:** medium

It looks like that the only difference between `isascii()` and `isalpha()` functions that matters in this case is that `isascii()` returns `True` for empty strings. Is that the only use case for this function?

**Comment by aregmelqonyan** [comment]
No, there are more use cases. Password can contain only english letters, whereas isalpha() function returns True for other language letters too.
